name: DiscordMessenger
version: '${project.version}'
main: com.pepedevs.discordmessenger.DiscordMessenger
api-version: 1.13
softdepend:
  - CMI
  - AdvancedBan
  - GodsEye
  - PlayerAuctions
  - VotingPlugin
  - BanItem
  - PlaceholderAPI
  - PvPManager
  - ExcellentCrates